language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - lcov
  coverity_scan:
    project:
      name: "Stalker2106x/MenuFramework"
      description: "XML/Lua Menu Framework"
    notification_email: contact@maximemartens.fr
    build_command_prepend: "before_script"
    build_command: "script"
    branch_pattern: coverity_scan

before_script:
  - gem install coveralls-lcov
  - export CC=gcc-6
  - export CXX=g++-6
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Coverage

script:
  - make

after_success:
  - cd ../bin/
  - ./MenuFramework_test
  - lcov --directory ../ --capture --output-file coverage.info
  # filter out system and extra files.
  - lcov --remove coverage.info '/thirdparty/*' '/test/*' '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  - coveralls-lcov coverage.info