language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
  coverity_scan:
    project:
      name: "Stalker2106x/MenuFramework"
      description: "XML/Lua Menu Framework"
    notification_email: contact@maximemartens.fr
    build_command_prepend: "before_script"
    build_command: "script"
    branch_pattern: coverity_scan

before_script:
  - pip install --user cpp-coveralls
  - export CC=gcc-6
  - export CXX=g++-6
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Coverage

script:
  - make

after_success:
  - coveralls --exclude thridparty --gcov-options '\-lp'