language: cpp

compiler:
  - gcc
  - clang

before_script:
  - cd thirdparty/luac/
  - mkdir build
  - cd build
  - cmake ..
  - cd ../../../
  - mkdir build
  - cd build
  - cmake ..

script: make && make test